name: PR Checker

on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened, synchronize]

env:
  action_repository: ${{ github.action_repository }}

jobs:
  check_commit_name_in_pr:
    if: github.head_ref != 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Print Details
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const res = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            console.log(JSON.stringify(res))
            console.log(head_ref: ${{ github.head_ref }})
            console.log(base_ref: ${{ github.base_ref }})
            console.log(env.action_repository: ${{ env.action_repository }})
            console.log(github.event: ${{ github.event }})
            console.log(github.event.pull_request: ${{ github.event.pull_request }})
            console.log(github.repository: ${{ github.repository }})
      - name: Check Commits
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            
            const regex = /^((build|chore|ci|docs?|feat|fix|perf|refactor|rft|style|test|i18n)[\:\.\(\,]|[Rr]evert|[Rr]elease)/;
            const invalidCommits = commits.filter(commit => !regex.test(commit.commit.message));
            
            console.log(`check ${commits.length} commit(s)`);
            
            if (invalidCommits.length > 0) {
              const invalidCommitNames = invalidCommits.map(commit => commit.commit.message);
              core.setFailed(`Invalid commit names found: ${JSON.stringify(invalidCommitNames)}`);
            }
